# Generated by Django 3.2.16 on 2025-03-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticpage',
            options={'verbose_name': 'статичная страница', 'verbose_name_plural': 'статичные страницы'},
        ),
    ]
